import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import { getProfile } from "../lib/api";
import styles from "../styles/Home.module.css";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR("/api/contributors", fetcher);
  console.log({ data });
  return (
    <div className={styles.container}>
      <Head>
        <title>Contributors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Contributors page</a>
        </h1>

        <div className={styles.grid}>
          {data &&
            data.list.map((row) => (
              <Card key={row.name} profileName={row.name} />
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

function Card({ profileName }) {
  const { data, error, isLoading } = useSWR(profileName, getProfile);
  if (isLoading) {
    return null;
  }
  if (!data) {
    return null;
  }
  console.log({ data });
  const { avatar_url, name, html_url } = data;
  return (
    <a href="https://nextjs.org/docs" className={styles.card}>
      <Image
        className={styles.avatar}
        src={avatar_url}
        alt={`Avatar for ${name}`}
        width={150}
        height={150}
      />
      <p>
        Gracias{" "}
        <h2>
          <a className="link" href={html_url}>
            {name}
          </a>
        </h2>
      </p>
    </a>
  );
}
